//! Canonical scrambled-counter xorshift64* generator (API Surface C).
//!
//! Byte-identical to the Go port in `server/internal/rng` and pinned by
//! `api/rng.testvectors.txt`. Compiled to WASM (wasm-bindgen) it is the
//! incompressible-payload source the client streams in the upload measurement;
//! the server discards and counts those bytes.
//!
//! Generator (see the corpus header):
//!   next:  old = state; state = old + inc; return scramble(old)
//!   scramble(x): x ^= x>>12; x ^= x<<25; x ^= x>>27; return x * 0x2545F4914F6CDD1D
//! fill writes successive next() as little-endian u64; a tail < 8 bytes is the
//! low bytes of one more next() in little-endian order.

use wasm_bindgen::prelude::*;

/// xorshift64* output multiplier.
const SCRAMBLE_MUL: u64 = 0x2545_F491_4F6C_DD1D;

/// Canonical download-block parameters — match `rng.BlockSeed` / `rng.BlockInc`
/// (Go) and the first pair in `api/rng.testvectors.txt`.
pub const BLOCK_SEED: u64 = 0x9E37_79B9_7F4A_7C15;
pub const BLOCK_INC: u64 = 0x2545_F491_4F6C_DD1D;

#[inline]
fn scramble(mut x: u64) -> u64 {
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    x.wrapping_mul(SCRAMBLE_MUL)
}

/// A deterministic xorshift64* stream: a 64-bit additive counter whose
/// pre-increment state is scrambled into each output word. Stateful — successive
/// `fill_bytes` calls continue the same stream, so a streaming upload can refill
/// a reused buffer without re-seeding.
#[wasm_bindgen]
pub struct ScrambledCounterRng {
    state: u64,
    inc: u64,
}

#[wasm_bindgen]
impl ScrambledCounterRng {
    /// Construct from an initial state and increment (passed from JS as BigInts).
    #[wasm_bindgen(constructor)]
    pub fn new(seed: u64, inc: u64) -> ScrambledCounterRng {
        ScrambledCounterRng { state: seed, inc }
    }

    /// The next 64-bit output word; advances the counter.
    pub fn next_u64(&mut self) -> u64 {
        let old = self.state;
        self.state = old.wrapping_add(self.inc);
        scramble(old)
    }

    /// Fill `dst` with generated bytes: successive `next_u64()` little-endian,
    /// with a final partial word contributing its low bytes (little-endian).
    /// Advances the stream, so calling it again continues where it left off.
    pub fn fill_bytes(&mut self, dst: &mut [u8]) {
        let mut chunks = dst.chunks_exact_mut(8);
        for c in &mut chunks {
            c.copy_from_slice(&self.next_u64().to_le_bytes());
        }
        let rem = chunks.into_remainder();
        if !rem.is_empty() {
            let word = self.next_u64().to_le_bytes();
            rem.copy_from_slice(&word[..rem.len()]);
        }
    }
}

/// The canonical download-block seed/inc, exported so JS can reproduce the
/// server's block bytes if it ever needs parity (e.g. a WASM download path).
#[wasm_bindgen]
pub fn block_seed() -> u64 {
    BLOCK_SEED
}

#[wasm_bindgen]
pub fn block_inc() -> u64 {
    BLOCK_INC
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse `api/rng.testvectors.txt` and assert the Rust generator is
    /// byte-identical to the shared corpus — the same rows the Go port passes.
    /// This is the cross-language guarantee (Surface C).
    #[test]
    fn fill_bytes_matches_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../api/rng.testvectors.txt");
        let text = std::fs::read_to_string(path).expect("read corpus");

        let mut rows = 0;
        for (lineno, line) in text.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = line.split('|').map(str::trim).collect();
            assert_eq!(parts.len(), 4, "line {}: want 4 fields", lineno + 1);
            let seed: u64 = parts[0].parse().unwrap();
            let inc: u64 = parts[1].parse().unwrap();
            let n: usize = parts[2].parse().unwrap();
            let want = parts[3];

            let mut buf = vec![0u8; n];
            ScrambledCounterRng::new(seed, inc).fill_bytes(&mut buf);
            let got: String = buf.iter().map(|b| format!("{:02x}", b)).collect();
            assert_eq!(got, want, "line {}: seed={} inc={} n={}", lineno + 1, seed, inc, n);
            rows += 1;
        }
        assert!(rows > 0, "corpus had no rows");
    }

    /// The stream is continuous across fill_bytes calls: two 32-byte fills equal
    /// one 64-byte fill from the same seed (what a chunked upload relies on).
    #[test]
    fn fill_bytes_is_continuous() {
        let mut one = ScrambledCounterRng::new(BLOCK_SEED, BLOCK_INC);
        let mut long = vec![0u8; 64];
        one.fill_bytes(&mut long);

        let mut two = ScrambledCounterRng::new(BLOCK_SEED, BLOCK_INC);
        let mut a = vec![0u8; 32];
        let mut b = vec![0u8; 32];
        two.fill_bytes(&mut a);
        two.fill_bytes(&mut b);

        assert_eq!(&long[..32], &a[..]);
        assert_eq!(&long[32..], &b[..]);
    }
}
