import * as ts from "typescript";

type Comment = {
  end: number;
  kind: ts.SyntaxKind;
  start: number;
  startLine: number;
  endLine: number;
  directive: boolean;
};

type Group = {
  comments: Comment[];
  header: boolean;
};

const sourceRoots = new Set(["src", "browser", "e2e", "bench", "scripts"]);
const excludedParts = new Set([
  ".cache",
  ".svelte-kit",
  "build",
  "coverage",
  "dist",
  "node_modules",
  "out",
]);
const sourceExtensions = new Set([".cts", ".mts", ".ts", ".tsx"]);
const maxCommentLineLength = 120;

function isSourceFile(path: string): boolean {
  const parts = path.split("/");
  if (parts.some((part) => excludedParts.has(part))) return false;
  const extension = path.slice(path.lastIndexOf("."));
  return (
    sourceExtensions.has(extension) &&
    (parts.length === 1 || sourceRoots.has(parts[0]))
  );
}

async function sourceFiles(clientRoot: string): Promise<string[]> {
  const files: string[] = [];
  const glob = new Bun.Glob("**/*.{cts,mts,ts,tsx}");
  for await (const path of glob.scan({
    cwd: clientRoot,
    dot: true,
    onlyFiles: true,
  })) {
    if (isSourceFile(path)) files.push(path);
  }
  return files.sort();
}

function generatedMarker(comment: Comment, text: string): boolean {
  const body = text.slice(comment.start, comment.end).toLowerCase();
  return (
    body.includes("this file was automatically generated") ||
    body.includes("code generated by") ||
    body.includes("generated by") ||
    body.includes("@generated") ||
    body.includes("<auto-generated") ||
    (body.includes("generated") && body.includes("do not edit"))
  );
}

function isDirective(comment: Comment, text: string): boolean {
  let body = text.slice(comment.start, comment.end).trim();
  if (body.startsWith("///")) return true;
  if (body.startsWith("//")) body = body.slice(2);
  if (body.startsWith("/*")) body = body.slice(2);
  if (body.endsWith("*/")) body = body.slice(0, -2);
  body = body.trim();
  while (body.startsWith("*")) body = body.slice(1).trimStart();
  return body.startsWith("@ts-ignore") || body.startsWith("@ts-expect-error");
}

function protectedTokenRanges(file: ts.SourceFile): Array<[number, number]> {
  const ranges: Array<[number, number]> = [];
  function visit(node: ts.Node): void {
    if (
      node.kind === ts.SyntaxKind.RegularExpressionLiteral ||
      node.kind === ts.SyntaxKind.StringLiteral ||
      node.kind === ts.SyntaxKind.NoSubstitutionTemplateLiteral ||
      node.kind === ts.SyntaxKind.TemplateHead ||
      node.kind === ts.SyntaxKind.TemplateMiddle ||
      node.kind === ts.SyntaxKind.TemplateTail
    ) {
      ranges.push([node.getStart(file), node.end]);
    }
    ts.forEachChild(node, visit);
  }
  visit(file);
  return ranges;
}

function maskRanges(text: string, ranges: Array<[number, number]>): string {
  let masked = text;
  for (const [start, end] of ranges) {
    let replacement = "";
    for (let position = start; position < end; position++) {
      const character = text[position];
      replacement += character === "\r" || character === "\n" ? character : " ";
    }
    masked = masked.slice(0, start) + replacement + masked.slice(end);
  }
  return masked;
}

function scanComments(path: string, text: string): Group[] {
  const scriptKind = path.endsWith(".tsx")
    ? ts.ScriptKind.TSX
    : ts.ScriptKind.TS;
  const file = ts.createSourceFile(
    path,
    text,
    ts.ScriptTarget.Latest,
    true,
    scriptKind,
  );
  const ranges = protectedTokenRanges(file);
  const scannerText = maskRanges(text, ranges);
  const languageVariant =
    scriptKind === ts.ScriptKind.TSX
      ? ts.LanguageVariant.JSX
      : ts.LanguageVariant.Standard;
  const scanner = ts.createScanner(
    ts.ScriptTarget.Latest,
    false,
    languageVariant,
    scannerText,
  );
  const comments: Comment[] = [];
  let token = scanner.scan();
  while (token !== ts.SyntaxKind.EndOfFileToken) {
    if (
      token === ts.SyntaxKind.SingleLineCommentTrivia ||
      token === ts.SyntaxKind.MultiLineCommentTrivia
    ) {
      const start = scanner.getTokenPos();
      const end = scanner.getTextPos();
      const startLine = file.getLineAndCharacterOfPosition(start).line;
      const endLine = file.getLineAndCharacterOfPosition(
        Math.max(start, end - 1),
      ).line;
      const comment = {
        kind: token,
        start,
        end,
        startLine,
        endLine,
        directive: false,
      };
      comment.directive = isDirective(comment, text);
      comments.push(comment);
    }
    token = scanner.scan();
  }

  let firstCode = text.length;
  const codeScanner = ts.createScanner(
    ts.ScriptTarget.Latest,
    false,
    languageVariant,
    scannerText,
  );
  let codeToken = codeScanner.scan();
  while (codeToken !== ts.SyntaxKind.EndOfFileToken) {
    if (
      codeToken !== ts.SyntaxKind.WhitespaceTrivia &&
      codeToken !== ts.SyntaxKind.NewLineTrivia &&
      codeToken !== ts.SyntaxKind.SingleLineCommentTrivia &&
      codeToken !== ts.SyntaxKind.MultiLineCommentTrivia
    ) {
      firstCode = codeScanner.getTokenPos();
      break;
    }
    codeToken = codeScanner.scan();
  }
  if (
    comments.some(
      (comment) => comment.start < firstCode && generatedMarker(comment, text),
    )
  ) {
    return [];
  }

  const groups: Group[] = [];
  for (const comment of comments) {
    const previous = groups.at(-1)?.comments.at(-1);
    const adjacent =
      previous &&
      previous.kind === ts.SyntaxKind.SingleLineCommentTrivia &&
      comment.kind === ts.SyntaxKind.SingleLineCommentTrivia &&
      comment.startLine === previous.endLine + 1 &&
      text.slice(previous.end, comment.start).trim() === "";
    if (adjacent) {
      groups.at(-1)?.comments.push(comment);
    } else {
      groups.push({ comments: [comment], header: false });
    }
  }

  let headerSeen = false;
  for (const group of groups) {
    const prose = group.comments.filter((comment) => !comment.directive);
    group.header =
      !headerSeen && prose.length > 0 && group.comments[0].start < firstCode;
    if (prose.length > 0) headerSeen = true;
  }
  return groups;
}

function commentErrors(path: string, text: string): string[] {
  const groups = scanComments(path, text);
  const errors: string[] = [];
  const sourceLines = text.split("\n");
  for (const group of groups) {
    const prose = group.comments.filter((comment) => !comment.directive);
    if (prose.length === 0) continue;
    const lines = prose.reduce(
      (total, comment) => total + comment.endLine - comment.startLine + 1,
      0,
    );
    const maximum = group.header ? 3 : 1;
    if (lines > maximum) {
      errors.push(
        `${path}:${prose[0].startLine + 1}: comment group spans ${lines} physical lines (maximum ${maximum})`,
      );
    }
    for (const comment of prose) {
      for (let line = comment.startLine; line <= comment.endLine; line++) {
        const sourceLine = sourceLines[line].replace(/\r$/, "");
        if (sourceLine.length > maxCommentLineLength) {
          errors.push(
            `${path}:${line + 1}: prose comment line exceeds ${maxCommentLineLength} characters`,
          );
        }
      }
    }
  }
  return errors;
}

async function checkFile(path: string, root: string): Promise<string[]> {
  return commentErrors(
    `client/${path}`,
    await Bun.file(`${root}/${path}`).text(),
  );
}

function selfTests(): void {
  const longParagraph = `// ${"word ".repeat(24)}`;
  const fixtures: Array<[string, string, number]> = [
    [
      "literal contents",
      `const string = "// fake";
const template = \`/* fake */\`;
const interpolated = \`https://example.test/**/\${string}\`;
const regex = /[/*]/; // real
`,
      0,
    ],
    [
      "directive between prose",
      `const value = 1;
// first
// @ts-ignore
// @ts-expect-error
// second
`,
      1,
    ],
    [
      "template expression comment",
      `const value = \`https://example.test/**/\${string /*
 expression
 */}\`;
`,
      1,
    ],
    [
      "file header",
      `// one
// two
// three
const value = 1;
`,
      0,
    ],
    ["concatenated long paragraph", `${longParagraph}\nconst value = 1;\n`, 1],
    ["concise comment", "// concise\nconst value = 1;\n", 0],
    [
      "generated preamble",
      `// Code generated by fixture. DO NOT EDIT.
// generated prose
// generated prose
// generated prose
// generated prose
const value = 1;
`,
      0,
    ],
    [
      "later generated marker",
      `const value = 1;
// Code generated by fixture. DO NOT EDIT.
// prose after code
`,
      1,
    ],
  ];
  for (const [name, text, count] of fixtures) {
    const actual = commentErrors("fixture.ts", text).length;
    if (actual !== count) {
      throw new Error(`${name}: expected ${count} errors, got ${actual}`);
    }
  }
}

const root = new URL("..", import.meta.url).pathname.slice(0, -1);
selfTests();
const errors: string[] = [];
for (const path of await sourceFiles(root)) {
  errors.push(...(await checkFile(path, root)));
}
if (errors.length > 0) {
  console.error(errors.join("\n"));
  process.exitCode = 1;
}
