version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ["*"]
  - package-ecosystem: bun
    directory: /client
    schedule:
      interval: weekly
    groups:
      client-deps:
        patterns: ["*"]
