/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BaseUrl = string;

/**
 * Logical server discovery with independently selectable throughput and latency endpoints.
 */
export interface Preflight {
  server: {
    name: string;
    location?: string;
  };
  engineVersion: string;
  generation: string;
  capabilities: {
    /**
     * Fresh owner-checked receiver windows are available.
     */
    uploadCheckpoint?: boolean;
    throughput: ThroughputEndpoint[];
    latency: LatencyEndpoint[];
  };
}
export interface ThroughputEndpoint {
  baseUrl: BaseUrl;
  transport: "fetch-stream" | "webtransport" | "webtransport-datagram";
  protocol: "http1" | "http2" | "http3" | "negotiated";
}
export interface LatencyEndpoint {
  baseUrl: BaseUrl;
  transport: "websocket" | "webtransport";
}
