/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response body of GET /preflight. The client maps the InfraInfo fields onto its InfraInfo type (client/src/lib/runner/contract.ts) and stashes `capabilities` for transport negotiation. The server serves/sinks raw bytes; this document carries no rates.
 */
export interface Preflight {
  /**
   * The client's public IP as observed by the server (X-Forwarded-For first hop, else the socket remote address).
   */
  clientIp: string;
  server: {
    name: string;
    host: string;
    port: number;
    /**
     * Optional human/region label (e.g. "fra").
     */
    location?: string;
  };
  /**
   * Optional server-side pre-test RTT hint in ms. 0 when no ping endpoint has run yet (e.g. Stage 1).
   */
  preTestPingMs: number;
  /**
   * Server build/engine version (ldflags-injected).
   */
  engineVersion: string;
  /**
   * The HTTP protocol this preflight response was served over, e.g. "http/1.1", "h2", "h3".
   */
  protocolNegotiated: string;
  /**
   * What this server currently supports, so the client negotiates rather than assumes.
   */
  capabilities: {
    /**
     * Externally-reachable origins the client should target per transport. Env-driven so the values are correct behind a reverse proxy. `null` means that origin is not enabled.
     */
    origins: {
      /**
       * HTTP/1.1 cleartext origin (default, e.g. http://host:8080).
       */
      h1: string | null;
      /**
       * HTTP/1.1+TLS origin (e.g. https://host:8443); null until enabled.
       */
      tls: string | null;
      /**
       * HTTP/3 + WebTransport origin (e.g. https://host:8443); null until enabled.
       */
      h3: string | null;
    };
    /**
     * Which client-side transports this server can currently service. Honest per build stage.
     */
    transports: {
      /**
       * fetch streaming download+upload.
       */
      fetchStream: boolean;
      /**
       * WebSocket latency bus (/ws/ping).
       */
      websocket: boolean;
      /**
       * WebTransport datagrams + uni-streams.
       */
      webtransport: boolean;
    };
    /**
     * Stable endpoint paths, advertised so the client never hardcodes them.
     */
    endpoints: {
      download: string;
      upload: string;
      /**
       * HTTP endpoint that mints an opaque upload-session token during upload warmup. The client echoes that token as ?id= on POST /upload and GET /ws/upload for that upload stage.
       */
      uploadSession: string;
      wsPing: string;
      /**
       * WebSocket upload-progress bus: streams server-measured BYTES_RECEIVED/UPLOAD_COMPLETE for the test ?id=.
       */
      wsUpload: string;
      wtPing: string;
      wtDownload: string;
      wtUpload: string;
    };
  };
}
