/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Logical-server discovery returned by GET /preflight. Bulk transfer targets and interactive message channels are independently selectable; connection evidence comes from GET /probe on the selected transfer target.
 */
export interface Preflight {
  server: {
    name: string;
    host: string;
    port: number;
    location?: string;
  };
  engineVersion: string;
  capabilities: {
    transfers: TransferTarget[];
    channels: ChannelTarget[];
  };
}
export interface TransferTarget {
  id: string;
  origin: string;
  transport: "fetch-stream";
  protocol: "http1" | "http2" | "http3";
  tls: boolean;
  routes: TransferRoutes;
}
export interface TransferRoutes {
  probe: string;
  download: string;
  upload: string;
  uploadSession: string;
}
export interface ChannelTarget {
  id: string;
  origin: string;
  transport: "websocket" | "webtransport";
  protocol: "http1" | "http2" | "http3";
  tls: boolean;
  routes: ChannelRoutes;
}
export interface ChannelRoutes {
  latency: string | null;
  uploadProgress: string | null;
}
