/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The originating operator's bounded server catalogue. The first entry is synthesized self. IDs and canonical origins are unique; every defaultSelection ID must exist. Runtime validation also enforces UTF-8 byte limits and canonical HTTP(S) origins.
 */
export interface ServerCatalog {
  /**
   * @minItems 1
   * @maxItems 4
   */
  defaultSelection: [string] | [string, string] | [string, string, string] | [string, string, string, string];
  /**
   * @minItems 1
   * @maxItems 32
   */
  servers: [ServerEntry, ...ServerEntry[]];
}
export interface ServerEntry {
  id: string;
  url: string;
  name: string;
  location?: string;
  /**
   * @maxItems 32
   */
  additionalOrigins?: string[];
}
