// Command authassets bakes the auth UI files into Go string constants.
// Its go:generate directive sets the working directory to internal/auth.
// The relative asset and output paths resolve against that directory.
package main

import (
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

var assets = []struct{ constant, file string }{
	{"authCSS", "auth.css"},
	{"authThemeJS", "theme.js"},
	{"authPendingJS", "pending.js"},
	{"loginHTML", "login.tmpl"},
	{"cliHTML", "cli.tmpl"},
	{"cliDoneHTML", "cli-done.tmpl"},
	{"continueHTML", "continue.tmpl"},
}

func main() {
	root := filepath.Join("..", "..", "..", "client", "src", "auth")
	var source strings.Builder
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage auth\n\n")
	for _, asset := range assets {
		contents, err := os.ReadFile(filepath.Join(root, asset.file))
		if err != nil {
			panic(err)
		}
		source.WriteString("const " + asset.constant + " = " + strconv.Quote(string(contents)) + "\n")
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("assets_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
