package main

import (
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

var assets = []struct{ constant, file string }{
	{"authCSS", "auth.css"},
	{"authThemeJS", "theme.js"},
	{"loginHTML", "login.tmpl"},
	{"cliHTML", "cli.tmpl"},
	{"cliDoneHTML", "cli-done.tmpl"},
	{"continueHTML", "continue.tmpl"},
}

func main() {
	root := filepath.Join("..", "..", "..", "client", "src", "auth")
	source := "// Code generated by go generate; DO NOT EDIT.\n\npackage auth\n\n"
	for _, asset := range assets {
		value, err := os.ReadFile(filepath.Join(root, asset.file))
		if err != nil {
			panic(err)
		}
		source += "const " + asset.constant + " = " + strconv.Quote(string(value)) + "\n"
	}
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("assets_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
