[workspace]
members = ["core", "server", "client", "net", "http3"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.99.0"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
base64 = { version = "0.23.1", default-features = false, features = ["std"] }
miniz_oxide = { version = "0.9.1", default-features = false, features = ["with-alloc"] }
rustfs-mimalloc = "=0.5.6"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.ci]
inherits = "release"
lto = false
codegen-units = 16

[patch.crates-io]
h2 = { git = "https://github.com/zR-JB/h2", rev = "238744966508e206bbcc81f13994d9637b8449d0" }
noq = { git = "https://github.com/zR-JB/noq", rev = "6abfdf0f8d7ef2750fcf1a15710880800b64a752" }
