[workspace]
members = ["core", "server", "client", "net", "webtransport"]
resolver = "3"

[workspace.package]
version = "0.8.6"
edition = "2024"
rust-version = "1.98.1"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
h3-noq = { git = "https://github.com/zR-JB/h3", rev = "03874beb50d065f4ac8f946ddb7814d2432b7527" }
base64 = { version = "0.23.1", default-features = false, features = ["std"] }
miniz_oxide = { version = "0.9.1", default-features = false, features = ["with-alloc"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.ci]
inherits = "release"
lto = false
codegen-units = 16

[patch.crates-io]
h2 = { git = "https://github.com/zR-JB/h2", rev = "ece53421ec31270ff843a783bcdf244bd6c5eef7" }
h3 = { git = "https://github.com/zR-JB/h3", rev = "03874beb50d065f4ac8f946ddb7814d2432b7527" }
noq = { git = "https://github.com/zR-JB/noq", rev = "17cd99748fb80a65753ffffddde77b896e3f6f75" }
