[workspace]
members = ["core", "server", "client", "net", "http3"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.98.1"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
base64 = { version = "0.23.1", default-features = false, features = ["std"] }
miniz_oxide = { version = "0.9.1", default-features = false, features = ["with-alloc"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.ci]
inherits = "release"
lto = false
codegen-units = 16

[patch.crates-io]
h2 = { git = "https://github.com/zR-JB/h2", rev = "ece53421ec31270ff843a783bcdf244bd6c5eef7" }
noq = { git = "https://github.com/zR-JB/noq", rev = "b34035dcfc96789f8269a5e080a6513e981f4904" }
