package legal

import (
	"bytes"
	_ "embed"
)

// tuiLegal is generated by legalgen from the same project metadata and TUI inventory used for release archives.
//go:embed assets/TUI_LEGAL.txt
var tuiLegal []byte

// TUIReport returns the generated legal report for graphite-meter-client --legal.
func TUIReport() []byte {
	return bytes.Clone(tuiLegal)
}
