package legal

import (
	"bytes"
	_ "embed"
)

// tuiLegal is generated by legalgen from the same project metadata and TUI
// inventory used for release archives. Keeping the report as one generated
// asset prevents the binary convenience flag from growing a second legal
// database.
//
//go:embed assets/TUI_LEGAL.txt
var tuiLegal []byte

// TUIReport returns the generated legal report for graphite-meter-client
// --legal. The returned copy prevents callers from mutating the embedded data.
func TUIReport() []byte {
	return bytes.Clone(tuiLegal)
}
