package commentpolicy

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
)

type violation struct {
	path string
	line int
}

const maxCommentLineLength = 120

type proseLine struct {
	line   int
	length int
}

func TestModuleGoComments(t *testing.T) {
	root := moduleRoot()
	paths, err := moduleGoFiles(root)
	if err != nil {
		t.Fatal(err)
	}

	var violations []violation
	for _, path := range paths {
		source, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		violations = append(violations, check(path, source)...)
	}
	slices.SortFunc(violations, func(a, b violation) int {
		if a.path != b.path {
			return strings.Compare(a.path, b.path)
		}
		return a.line - b.line
	})
	for _, violation := range violations {
		t.Errorf("%s:%d: prose comment group exceeds its line limit", violation.path, violation.line)
	}
}

func TestCheckCommentFixtures(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want []violation
	}{
		{
			name: "file comment allows three lines",
			src:  "// one\n// two\n// three\npackage fixture\n",
		},
		{
			name: "ordinary group allows one line",
			src:  "package fixture\n\n// one\n// two\nfunc f() {}\n",
			want: []violation{{path: "fixture.go", line: 4}},
		},
		{
			name: "concatenated long paragraph is rejected",
			src:  "package fixture\n\n// " + strings.Repeat("word ", 24) + "\nfunc f() {}\n",
			want: []violation{{path: "fixture.go", line: 3}},
		},
		{
			name: "concise comment passes",
			src:  "package fixture\n\n// concise\nfunc f() {}\n",
		},
		{
			name: "block comment counts physical prose lines",
			src:  "package fixture\n\n/*\n one\n two\n*/\nfunc f() {}\n",
			want: []violation{{path: "fixture.go", line: 5}},
		},
		{
			name: "directives do not exempt adjacent prose",
			src:  "package fixture\n\n// one\n//go:build fixture\n// two\nfunc f() {}\n",
			want: []violation{{path: "fixture.go", line: 5}},
		},
		{
			name: "generated file is skipped",
			src:  "// Code generated by fixture; DO NOT EDIT.\n// one\n// two\npackage fixture\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got := check("fixture.go", []byte(test.src))
			if !slices.Equal(got, test.want) {
				t.Fatalf("check() = %v, want %v", got, test.want)
			}
		})
	}
}

func moduleRoot() string {
	_, filename, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(filename), "..", ".."))
}

func moduleGoFiles(root string) ([]string, error) {
	var paths []string
	for _, tree := range []string{"cmd", "internal"} {
		err := filepath.WalkDir(filepath.Join(root, tree), func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil || entry.IsDir() || filepath.Ext(path) != ".go" {
				return walkErr
			}
			paths = append(paths, filepath.ToSlash(strings.TrimPrefix(path, root+string(filepath.Separator))))
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	slices.Sort(paths)
	return paths, nil
}

func check(path string, source []byte) []violation {
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, path, source, parser.ParseComments)
	if err != nil {
		return []violation{{path: path, line: 1}}
	}
	if ast.IsGenerated(file) {
		return nil
	}

	packageLine := fileSet.Position(file.Name.Pos()).Line
	firstHeader := true
	var violations []violation
	sourceLines := strings.Split(string(source), "\n")
	for _, group := range file.Comments {
		lines := proseLines(fileSet, group, sourceLines)
		if len(lines) == 0 {
			continue
		}
		limit := 1
		if firstHeader && fileSet.Position(group.Pos()).Line < packageLine {
			limit = 3
		}
		firstHeader = false
		seen := make(map[int]bool)
		for _, line := range lines {
			if line.length > maxCommentLineLength && !seen[line.line] {
				violations = append(violations, violation{path: path, line: line.line})
				seen[line.line] = true
			}
		}
		for _, line := range lines[min(limit, len(lines)):] {
			if !seen[line.line] {
				violations = append(violations, violation{path: path, line: line.line})
			}
		}
	}
	return violations
}

func proseLines(fileSet *token.FileSet, group *ast.CommentGroup, sourceLines []string) []proseLine {
	var lines []proseLine
	for _, comment := range group.List {
		if directive(comment.Text) {
			continue
		}
		start := fileSet.Position(comment.Pos()).Line
		parts := strings.Split(comment.Text, "\n")
		for offset, part := range parts {
			if isProse(part, comment.Text, offset, len(parts)) {
				line := start + offset
				length := len(strings.TrimSuffix(sourceLines[line-1], "\r"))
				lines = append(lines, proseLine{line: line, length: length})
			}
		}
	}
	return lines
}

func directive(text string) bool {
	text = strings.TrimSpace(text)
	return strings.HasPrefix(text, "//go:") ||
		strings.HasPrefix(text, "//line") ||
		strings.HasPrefix(text, "//nolint") ||
		strings.HasPrefix(text, "// Code generated")
}

func isProse(part, whole string, offset, count int) bool {
	part = strings.TrimSpace(part)
	if count == 1 {
		part = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(part, "/*"), "*/"))
	} else {
		if offset == 0 {
			part = strings.TrimSpace(strings.TrimPrefix(part, "/*"))
		}
		if offset == count-1 {
			part = strings.TrimSpace(strings.TrimSuffix(part, "*/"))
		}
		part = strings.TrimSpace(strings.TrimPrefix(part, "*"))
	}
	if strings.HasPrefix(strings.TrimSpace(whole), "//") {
		part = strings.TrimSpace(strings.TrimPrefix(part, "//"))
	}
	return part != ""
}
