"""Generate the embedded authentication assets; Go owns only output formatting."""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

ASSETS = (
    ('authCSS', 'auth.css'), ('authThemeJS', 'theme.js'), ('authPendingJS', 'pending.js'),
    ('loginHTML', 'login.tmpl'), ('cliHTML', 'cli.tmpl'), ('cliDoneHTML', 'cli-done.tmpl'),
    ('continueHTML', 'continue.tmpl'),
)


def generate(repo: Path) -> bytes:
    source = '// Code generated by go generate; DO NOT EDIT.\n\npackage auth\n\n'
    for constant, name in ASSETS:
        # JSON string escapes are valid Go escapes for these UTF-8 text assets.
        value = (repo / 'client/src/auth' / name).read_bytes().decode()
        source += f'const {constant} = {json.dumps(value, ensure_ascii=False)}\n'
    return subprocess.run(['gofmt'], input=source.encode(), capture_output=True, check=True).stdout


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo', type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    repo: Path = args.repo.resolve()
    destination = repo / 'go/internal/auth/assets_generated.go'
    destination.write_bytes(generate(repo))


if __name__ == '__main__':
    main()
